### ISSUE TITLE
Method onClick's problem

### ISSUE THREAD

**Issue by Kyren223** [upperlevel/book-api#29]
What if I want to execute a custom method when the player clicks on something in the book?
How can I achieve that?
I tried searching and stuff but I couldn't figure it out.
I want that when a player clicks it'll run a method within my plugin that does stuff, not necessarily a command.

By the way you got a great API and it helped me a ton, I'd love if I could have your discord or something to better communicate with you about the problem and some more stuff.
My discord is Kyren223#8030

**Comment by SnowyCoder** [comment]
Thanks! We have a discord but it's not used much.
As far as I know there is no way to execute a function directly from a book click (book clicks are client-side while functions are server-side), So the easiest thing to do is to create a command and map your clicks to commands, 
This also comes in handy for power users of your plugin, it's faster to type a command than to skim and click a book

**Comment by Kyren223** [comment]
The problem is I am using a ton of very specific values per book,
The book that is being created is very specific, per item (that triggers the book to open) and even with the same item the values are constantly changing, when you click something on a book I want it to run functions with those specific values that change other values

The example is clicking a morph button, there are 3 of those in the book, each activates a different morph
And when a morph is activated it changes the values of the specific morph chosen to empty

I also don't want players to have access to those commands (that will activate the functions)

**Comment by SnowyCoder** [comment]
That's an intresting problem you have there,
The only way to communicate things back to the server is with a command, so you could make a command with all of the specific values, but it will also be writable by a user (altough not so easily).
If you want to be extra-sure that the users don't type the command themselves you can borrow some concepts from web-development (maybe you could pack the parameters in a json and encrypt it with a private key?).

If you want you can create a custom framework to use functions on clicks by registering functions on a hashmap, ex:
When the book is open, the book has 3 on-click functions, so we will register 0 -> function 1, 1 -> function 2 , 2 -> function 3.
When we click the first text the user will run a command like `/customcommand 1` (for function 2).
The command will search the hashmap of that user for that number, and if it's present it will execute that function.
After the book is closed the hashmap should be cleaned (so that the user doesn't execute the function by themselves).

A lightweight version of this is specific for your use case is to have a custom command that sets the morph:
If you have morphs A, B, C, you could have a command `/setmorph <A|B|C>` that when invoked will change the values of the morph internally.
You should also make checks on the command though: (if user hasn't bought morph C `/setmorph C` should not work)

I'm sorry, it's quite hard but minecraft isn't designed for extensions, so we have to work around a lot of stuff.

**Comment by SnowyCoder** [comment]
Another path you may take is with inventory-based GUIs, servers can know when a user interacts with the inventory so we don't have to do commands to work around it, 
I've been out of bukkit development since some years now, so there should be better solutions, but we've made a custom GUI library in our [uppercore](https://github.com/upperlevel/uppercore) lib (it's not supported now, there should be other ones out there),

**Comment by flannelbum** [comment]
Chiming in here as I had to solve this for myself and under the context of unique books for players.  The end result is I generate tokens (a short string of numbers and letters) for each command and save each in a hashmap.  The plugin will then listen for its generic command and the token as a param.  The tokens are all generated on-the-fly each time a player opens a book and all are destroyed when they execute a command.  This makes it so a player is very unlikely to guess a token and there are no "shared" books - player will only ever see their book when they open it.  I am not claiming to be good at coding but I offer the work for you to rip or draw inspiration: [https://github.com/flannelbum/Bookmarks](https://github.com/flannelbum/Bookmarks)

**Comment by Kyren223** [comment]
Yea I have now came up with kind of a solution that will be really hard for a player to guess
As commands don't have autocomplete by default they can't really know what parameters they should put
And for the commands I need the specific variables for I am using the book's key, the key id (generated uuid)
Which is used to link the item to a custom object which stores the data and now also to execute a command on that specific thing

I am facing now another problem thought, when reloading/restarting the server the book becomes invalid for some reason?
I am checking an interact event with a custom item (that has the id (key) stored in PDC) and using that PDC getting the custom object and with that object opening a new book each time, so it shouldn't get outdated by restarting as it's each time using an object to generate a specific book?

**Comment by SnowyCoder** [comment]
I don't know what is a PDC, but are you using a HashMap? You might want to persist that hashmap

**Comment by Kyren223** [comment]
PDC is persistent data container, it's a property of an ItemStack object
It lets you store values, in my case a string which is the ID that determines the linked object that stores the data
Then I am using the object to open the book with specific values

I have done another item that just uses the item and object and it works file, what's breaking is the book
The book's values doesn't update for some reason

**Comment by SnowyCoder** [comment]
I can't debug it without having the code, it doesn't seem to be related to be related to this library though

**Comment by Kyren223** [comment]
Yep, I have fixed it, a dumb problem, forgot to call the saving and loading method for the morph object that stores the data lol

**Comment by SnowyCoder** [comment]
Closing the issue to keep this repo clean, if you have any other questions ask them!
